### ISSUE TITLE
Not working on Ubuntu after version 1.1.4

### ISSUE THREAD

**Issue by michael-1003** [edoli/edolview#2]
After edolview version 1.1.4, application does NOT run on Ubuntu. (It works on Windows)
It does not print or run anything.
Maybe https://github.com/edoli/edolview/commit/db11b80a3c242063b80a4d581efc93ee91517b6d caused some problem in Ubuntu? Not sure.

**Comment by edoli** [comment]
I checked the issue and found that name of OpenCV library for linux was not correct. The issue should be solved in latest version.

**Comment by michael-1003** [comment]
Thanks. With the latest release (1.4.5), now program runs. But when I put any image file (by both drag-drop or providing input path), it shows following error and crashes.
```
com.badlogic.gdx.utils.GdxRuntimeException: java.lang.ExceptionInInitializerError
	at com.badlogic.gdx.backends.lwjgl3.MyLwjgl3Application.<init>(MyLwjgl3Application.java:99)
	at kr.edoli.edolview.MainKt.main(Main.kt:70)
Caused by: java.lang.ExceptionInInitializerError
	at kr.edoli.edolview.ui.TextureGenerator.floatTextureDataFromMat(TextureGenerator.kt:52)
	at kr.edoli.edolview.ui.TextureGenerator$MatTexture.<init>(TextureGenerator.kt:61)
	at kr.edoli.edolview.ui.TextureGenerator.load(TextureGenerator.kt:92)
	at kr.edoli.edolview.ui.ImageViewer.updateTexture(ImageViewer.kt:397)
	at kr.edoli.edolview.ui.ImageViewer.access$updateTexture(ImageViewer.kt:33)
	at kr.edoli.edolview.ui.ImageViewer$2.invoke(ImageViewer.kt:72)
	at kr.edoli.edolview.ui.ImageViewer$2.invoke(ImageViewer.kt:70)
	at kr.edoli.edolview.util.ObservableList.subscribeValue$lambda-1(ObservableList.kt:45)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
	at kr.edoli.edolview.util.ObservableList.update(ObservableList.kt:94)
	at kr.edoli.edolview.util.ObservableList.update(ObservableList.kt:73)
	at kr.edoli.edolview.ImContext$3.invoke(ImContext.kt:190)
	at kr.edoli.edolview.ImContext$3.invoke(ImContext.kt:183)
	at kr.edoli.edolview.util.ObservableValue.subscribe$lambda-1(ObservableValue.kt:25)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
	at kr.edoli.edolview.util.ObservableValue.update(ObservableValue.kt:52)
	at kr.edoli.edolview.ImContext$2.invoke(ImContext.kt:176)
	at kr.edoli.edolview.ImContext$2.invoke(ImContext.kt:170)
	at kr.edoli.edolview.util.ObservableValue.subscribe$lambda-1(ObservableValue.kt:25)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
	at kr.edoli.edolview.util.ObservableValue.update(ObservableValue.kt:52)
	at kr.edoli.edolview.ImContext$1.invoke(ImContext.kt:140)
	at kr.edoli.edolview.ImContext$1.invoke(ImContext.kt:133)
	at kr.edoli.edolview.util.ObservableValue.subscribe$lambda-1(ObservableValue.kt:25)
	at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
	at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:135)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
	at kr.edoli.edolview.util.ObservableValue.update(ObservableValue.kt:52)
	at kr.edoli.edolview.ImContext.addAssetsFromFiles(ImContext.kt:321)
	at kr.edoli.edolview.ImContext.addAssetsFromFiles$default(ImContext.kt:319)
	at kr.edoli.edolview.MainKt$main$3.filesDropped(Main.kt:59)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window$5$1.run(Lwjgl3Window.java:138)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:373)
	at com.badlogic.gdx.backends.lwjgl3.MyLwjgl3Application.loop(MyLwjgl3Application.java:119)
	at com.badlogic.gdx.backends.lwjgl3.MyLwjgl3Application.<init>(MyLwjgl3Application.java:93)
	... 1 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @41c204a0
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at kr.edoli.edolview.util.NativeBuffer.<clinit>(NativeBuffer.kt:12)
	... 50 more
```

**Comment by edoli** [comment]
Thanks for checking the issue. I found that options for jvm was not updated for Linux. I fixed this issue and uploaded new release version [v1.4.6](https://github.com/edoli/edolview/releases/tag/v1.4.6)

**Comment by michael-1003** [comment]
It works perfect now. Thanks.
